[tool.poetry]
name = "antaryaami"
version = "0.1.0"
description = "Prediction Market AI Agent"
authors = ["bhanusanghi <bhanussanghi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langgraph = "^0.2.60"
langsmith = "^0.2.6"
langchain-openai = "^0.2.14"
ipython = "^8.31.0"
tavily-python = "^0.5.0"
langchain-community = "^0.3.13"
web3 = "^7.6.1"
py-clob-client = "^0.18.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
